from pydantic import BaseModel, Field

class Answer(BaseModel):
    """
    Represents an answer generated by the AI model.
    """
    text: str = Field(..., description="The generated answer text.")
    confidence: float = Field(..., description="Confidence score of the generated answer.")
    citations: list[str] = Field(default_factory=list, description="List of citations or references for the answer.")
    is_anserable: bool = Field(..., description="False if the document does not contain an answer to the question, True otherwise.")